---
title: "cdcmap"
author: "shuyue Xu"
date: "12/11/2021"
output: html_document
---

```{r}
library(graphics)
library("readxl")
library(dplyr)
library(tidyverse)
library(np)
library("lhs")
library(splines)
library(maps)
library(mapdata)
library("viridis")
library(RColorBrewer)
library(zoo)
library(GGally)
library(here)
library(highcharter)
library(MASS)
library(parcoords)
library(plotly)
library(scales)
library(usdata)
library(statebins)
library(usmap)
library(socviz)
library(ggrepel)
library(ggthemes)
library(grid)
library(lubridate)
library(tidytext)
library(jsonlite)
library(gridExtra)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
cdc = read_csv("data/United_States_COVID-19_Cases_and_Deaths_by_State_over_Time.csv")
cdc[,c('consent_cases')][cdc[,c('consent_cases')] == 'N/A'] = NA
cdc[,c('consent_deaths')][cdc[,c('consent_deaths')] == 'N/A'] = NA
```

```{r}
cdc$date = as.Date(cdc$submission_date, '%m/%d/%Y')
cdc$month = as.yearmon(format(as.Date(cdc$date), "%Y-%m"))
```

```{r}
head(cdc)
```


```{r}
cdc.month = cdc %>% mutate(state.mon = paste(state, as.character(month), sep='') ) %>% dplyr::group_by(state.mon) %>% dplyr::summarize(new_case = sum(new_case, na.rm = TRUE), new_death = sum(new_death, na.rm = TRUE), month = min(month), state=min(state)) %>% dplyr::rename(date = month) %>% select(-c(state.mon))
```

```{r}
cdc.month$statefull = state.name[match(cdc.month$state,state.abb)]
```
```{r}
cdc.month$statefull[cdc.month$state=="DC"] = "Maryland"
cdc.month$statefull[cdc.month$state=="NYC"] = "New York"
cdc.month  %>% group_by(statefull,date) %>% dplyr::summarise(new_case=sum(new_case),new_death=sum(new_death))
```


### new cases and deaths by State from 2020 Jan to 2021 Nov 



```{r}
cdcmonthcase = cdc.month %>%  
    do(item = list(
        state = first(.$statefull),
        sequence = .$new_case,
        value = first(.$new_case)
    ))%>%
    .$item
```
```{r}
highchart(type = "map") %>% 
  hc_add_series(data = cdcmonthcase,
                name = "Dem. Margin",
                mapData = usgeojson,
                joinBy = c("name","state"),
                borderWidth = 0.05,
                dataLabels = list(enabled = TRUE, format = "{point.properties.postalcode}")
                ) %>% 
  hc_colorAxis(minColor = "white", maxColor = "orange") %>%
  hc_title(text = "new cases from 2020 Apirl to 2021 Nov by state") %>%
  hc_add_theme(hc_theme_smpl()) %>%
  hc_motion(
    enabled = TRUE,
    axisLabel = "yearmonth",
    labels = as.character(sort(unique(cdc.month$date),decreasing = FALSE))
  )%>% 
  hc_legend(title = list(text = "new cases"), valueDecimals = 0, valueSuffix = "%") %>%
   hc_mapNavigation(enabled = TRUE) %>% hc_exporting(enabled = TRUE)
```

```{r}

cdcmonthdeath = cdc.month %>% 
    do(item = list(
        state = first(.$statefull),
        sequence = .$new_death,
        value = first(.$new_death)
    ))%>%
    .$item
```
```{r}
highchart(type = "map") %>% 
  hc_add_series(data = cdcmonthdeath,
                name = "Dem. Margin",
                mapData = usgeojson,
                joinBy = c("name","state"),
                borderWidth = 0.05,
                dataLabels = list(enabled = TRUE, format = "{point.properties.postalcode}")
                ) %>% 
  hc_colorAxis(minColor = "white", maxColor = "orange") %>%
  hc_title(text = "new deaths from 2020 Jan to 2021 Nov by state") %>%
  hc_add_theme(hc_theme_smpl()) %>%
  hc_motion(
    enabled = TRUE,
    axisLabel = "year",
    labels = as.character(sort(unique(cdc.month$date),decreasing = FALSE))
  )%>% 
  hc_legend(title = list(text = "new cases"), valueDecimals = 0, valueSuffix = "%") %>%
   hc_mapNavigation(enabled = TRUE) %>% hc_exporting(enabled = TRUE)
```