---
title: "Untitled"
author: "shuyue Xu"
date: "11/28/2021"
output: html_document
---

```{r}
library(googlesheets4)
#library(blsAPI)
library(rjson) 
library(dplyr)
library(ggplot2)
# library(lubridate)
```


```{r}
"
gs4_deauth()
data= googlesheets4::read_sheet('1fpEQ4wuuDlnfKokjKyRUrOcIwHUnIBmnBFubCUpnQ94',sheet='chained_data')
data1= googlesheets4::read_sheet('1fpEQ4wuuDlnfKokjKyRUrOcIwHUnIBmnBFubCUpnQ94',sheet='Sheet1')
"
chained= googlesheets4::read_sheet('1fpEQ4wuuDlnfKokjKyRUrOcIwHUnIBmnBFubCUpnQ94',sheet='chained')
```


```{r}
'
data$item_name <- chained$item_name[match(data$seriesID, chained$seriesid)]
data$item_name = as.factor(data$item_name)
data$value = as.numeric(data$value)
data$date <- paste(data$year, "-", substr(data$period,2,3), sep="")
'
#write.csv(data,"data/cpidata.csv", row.names = FALSE)
```


```{r}
data = read.csv("data/cpidata.csv")
```

```{r}
data$date <- as.yearmon(data$date, "%Y-%m")
```

```{r}
head(data)
```
```{r}
length(unique(data$date))
```


```{r, fig.height = 6}
data %>%
  ggplot( aes(x=date, y=value, group=item_name, color=item_name)) +
    geom_line() + theme(axis.text.x = element_text(angle = 90))
```

```{r}
don <- data %>% 
  filter(seriesID %in% c("SUUR0000SAT1","SUUR0000SAT", "SUUR0000SA0E","SUUR0000SAC","SUUR0000SETG","SUUR0000SETA01","SUUR0000SAE2")) 
don %>%
  ggplot( aes(x=date, y=value, group=item_name, color=item_name)) +
    geom_line() + theme(axis.text.x = element_text(angle = 90))
```
 "SUUR0000SA0E"(energy), "SUUR0000SAT1"(private transportation),"SUUR0000SAT"(transportation) decreases during the begining of covid-19 and then rises until now
 "SUUR0000SAC"(Commodities), "SUUR0000SETA01"(new vehicles) rises steadily 
 "SUUR0000SETG"(publictransportation) decreases ans then rise sharply during the start of 2021, then decrease sharply.
 "SUUR0000SAE2"(communication) no change

```{r}
# plot covid cases for top population states
plot_items <- function(data, items, feature, title, x=1, y=1) {
  # top_states = top_pop_states(covid, n)
  par(mfrow=c(x,y), mar=c(4,4,2,0.5)) # Setup grid, margins
  d = data %>% filter(item_name %in% items)
  ggplot(d, aes(x=date, y=value, group = item_name, color = item_name)) + geom_line() + theme(axis.text.x = element_text(angle=90)) + ggtitle(title)
    # plot(d$date, d[,feature], xlab = "Time", ylab = feature, main = paste("COVID cases in", state), pch = 20, cex = 0.5)
}
```



```{r}
# get spline model and return knots and spline predictions of training data
bspline.model <- function(data, dates, n.knots=6, degree=3) {
  X <- as.matrix(data)
  x=seq(0,1,length.out=nrow(X))
  knots = seq(0,1,length.out = n.knots-2)
  B = bs(x, knots = knots, degree = 3)[,1:(n.knots)]
  
  Bcoef = matrix(0,1,n.knots)
  Bcoef[1,] = solve(t(B)%*%B)%*%t(B)%*%as.matrix(X[,2])
  
  preds = (Bcoef%*%t(B))[1,]
  l = list()
  l[[1]] = Bcoef[1,]
  l[[2]] = preds
  return (l)
}
```

```{r}
# This function plots the bspline curves given the target items and parameters and returns knots for each item. 
plot.bspline <- function(data, items, feature, n.knots=6, degree=3, x=1, y=1) {
  par(mfrow=c(x,y), mar=c(4,4,2,0.5)) # Setup grid, margins
  data = data %>% subset(!is.na(data[, feature]))
  n = length(items)
  colors = rainbow(n)
  Bcoef.mat = matrix(0,n,n.knots)
  

  plot(c(min(data$date), max(data$date)), c(min(data[,feature]), max(data[,feature])), xlab = "Time", ylab = feature, main = "CPI item trends", type = "n", xaxt='n', pch = 20, cex = 0.5)
  for (i in 1:n) {
    d = data %>% filter(item_name == items[i]) %>% select(date, contains(feature)) %>% arrange(date)
    dates = d$date
    d$date = as.numeric(d$date)
    # points(d$date, d[,feature], pch = 20, cex = 0.5)
    
    l = bspline.model(d, dates, n.knots, degree)
    lines(dates, l[[2]], pch = 20, cex = 1, col = colors[i])
    Bcoef.mat[i,] = l[[1]]
    legend("topleft", legend=items, col=colors, lty=1, cex=0.2)
    ix <- seq(1, length(dates), by=60)
    fmt <- "%b-%Y" # format for axis labels
    labs <- format(dates[ix], fmt)
    axis(side = 1, at = dates[ix], labels = labs,  cex.axis = 0.8)
  }
  return (Bcoef.mat)
}
```

```{r}
all.items = unique(data$item_name)
all.items
```


```{r}
Bcoef.mat = plot.bspline(data, all.items, 'value', n.knots=6)
```

```{r}
wss <- function(k) {
  kmeans(as.data.frame(Bcoef.mat), k, nstart = 5)$tot.withinss
}
# Compute and plot wss for k = 2 to k = 15
k.values <- 2:10

# extract wss for 2-15 clusters
wss_values <- map_dbl(k.values, wss)
```



```{r}
sort.item.clusters <- function(clusters, sort.cluster.list) {
  clen = length(clusters)
  sort.clusters = 1:clen
  color.counter = 1
  for (c in 1:clen) {
    if (sort.cluster.list[[clusters[c]]] < 0) {
      sort.cluster.list[[clusters[c]]] = color.counter
      color.counter = color.counter + 1
    }
    sort.clusters[c] = sort.cluster.list[[clusters[c]]]
  }
  return (sort.clusters)
}
```


```{r}
for (i in 1:20) {
# Run K-means to cluster the knots of the states
  
  # choose the number of clusters we want and assign each state its closest cluster
  set.seed(i)

  for (k in 6) {
    cluster.num = k
    clusters = kmeans(as.data.frame(Bcoef.mat), cluster.num, nstart = 5)$cluster
    
    sort.cluster.list = list()
    for (j in 1:k) {
      sort.cluster.list[[j]] = -1
    }
    
    sort.clusters = sort.item.clusters(clusters, sort.cluster.list)

    items.df = data.frame(item = all.items, CLUSTER = sort.clusters)
    # write.csv(states.df, paste("./clusterings/cluster", i, ".csv", sep=""))
    
    item.cluster = list()
    for (i in 1:cluster.num) {
      item.cluster[[i]] = subset(items.df, CLUSTER==i)$item
    }
  }
}
```



```{r}
for (i in 1:length(item.cluster)) {
  print(plot_items(data, item.cluster[[i]], "value", "CPI Time Series"))
}
```

```{r}
#test = read.csv("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/5_OneCatSevNumOrdered.csv")

```

