---
title: "cdcbyregion"
author: "shuyue Xu"
date: "12/14/2021"
output: html_document
---

```{r}
cdc = read.csv("data/cdc.csv")
cdc = cdc %>% mutate(date=as.Date(date), month=as.yearmon(format(as.Date(date), "%Y-%m")))
```

```{r}
cdc_monthly_by_state = cdc %>% 
  select(month, state, new_death, new_case, conf_cases, tot_death) %>% 
  group_by(month, state) %>% 
  summarise(new_death=sum(new_death),new_case=sum(new_case), tot_cases=max(conf_cases), tot_death=max(tot_death))
cdc_monthly_by_state$statefull = state.name[match(cdc_monthly_by_state$state,state.abb)]
cdc_monthly_by_state = cdc_monthly_by_state %>% drop_na()
```

```{r, message=FALSE, warning=FALSE, echo=FALSE}
# 6
Northeast = c("Connecticut", "Massachusetts", "Maine", 
              "New Hampshire", "Rhode Island", "Vermont")

# 8
Mid.Atlantic = c("Delaware", "Maryland", 
                 "New Jersey", "New York", "Pennsylvania",
                 "Virginia", "West Virginia")

# 9
Southeast = c("Alabama", "Arkansas", "Florida",
                             "Georgia", "Louisiana", "Mississippi",
                             "North Carolina", "South Carolina", "Tennessee")

# 13
Midwest = c("Indiana", "Illinois", "Iowa", 
                           "Kansas", "Kentucky", "Michigan",
                           "Minnesota", "Missouri", "Nebraska",
                           "North Dakota", "Ohio", "South Dakota",
                           "Wisconsin")
# 4
Southwest = c("Arizona", "New Mexico", "Oklahoma", "Texas")

# 11
West = c("Alaska", "California", "Colorado", "Hawaii",
                        "Idaho", "Montana", "Nevada", "Oregon",
                        "Utah", "Washington", "Wyoming")

region.list <- list(Northeast, Mid.Atlantic, Southeast, Midwest, Southwest, West)
names(region.list) <- c('Northeast', 'Mid.Atlantic', 'Southeast', 'Midwest', 'Southwest', 'West')
```




```{r}
cdc_monthly_by_state$region = ifelse (cdc_monthly_by_state$statefull %in% Northeast, "Northeast",
                  ifelse (cdc_monthly_by_state$statefull%in% Mid.Atlantic, "Mid.Atlantic",
                  ifelse (cdc_monthly_by_state$statefull %in% Southeast, "Southeast",
                  ifelse (cdc_monthly_by_state$statefull %in% Midwest, "Midwest",
                  ifelse (cdc_monthly_by_state$statefull %in% Southwest, "Southwest",
                  ifelse (cdc_monthly_by_state$statefull %in% West, "West", "Other"
                          ))))))
```

```{r, message=FALSE, warning=FALSE, echo=FALSE, results='hide', fig.show='hide'}
cdcregion = cdc_monthly_by_state %>% select(region,month,statefull,tot_death)  %>% group_by(region,month) %>% dplyr::summarise(avgvalue=mean(tot_death),statefull = statefull)
```

```{r, message=FALSE, warning=FALSE, echo=FALSE, results='hide', fig.show='hide'}

cdcr = cdcregion %>% group_by(statefull)%>%arrange(month)%>% 
    do(item = list(
        state = first(.$statefull),
        sequence = .$avgvalue,
        value = first(.$avgvalue)
    ))%>%
    .$item
```
```{r, message=FALSE, warning=FALSE, echo=FALSE, results='hide', fig.show='hide'}
highchart(type = "map") %>% 
  hc_add_series(data =cdcr,
                name = "Margin",
                value = "dem_this_margin",
                borderColor = "black",
                borderWidth = 0.1,
                mapData = usgeojson,
                joinBy = c("name","state"),
                borderWidth = 0.05,
                dataLabels = list(enabled = TRUE, format = "{point.properties.postalcode}")
                ) %>% 
  hc_colorAxis(minColor = "white", maxColor = "orange") %>%
  hc_title(text = "total cases change from 2020 Jan to 2021 Nov by region") %>%
  hc_add_theme(hc_theme_smpl()) %>%
  hc_motion(
    enabled = TRUE,
    axisLabel = "yearmonth",
    labels = as.character(sort(unique(cdc_monthly_by_state$month),decreasing = FALSE))
  )%>% 
  hc_legend(title = list(text = "total cases"), valueDecimals = 0, valueSuffix = "%") %>%
   hc_mapNavigation(enabled = TRUE) %>% hc_exporting(enabled = TRUE)
```

